# Generated by Django 5.2.6 on 2026-07-08 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='artists', to='portfolio.tattoostyle'),
        ),
        migrations.AddField(
            model_name='reel',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='artists.artist'),
        ),
    ]
