# Generated by Django 5.2.6 on 2026-07-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_language_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Original English text', max_length=255, unique=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
