# Generated by Django 5.2.6 on 2026-07-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staticstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='portfolio_cards_square',
            field=models.BooleanField(default=True, help_text='Keeps portfolio listing cards aligned with no masonry gaps.', verbose_name='Use equal-height portfolio grid cards'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_portfolio_color_filters',
            field=models.BooleanField(default=False, verbose_name='Show portfolio colour buttons'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_portfolio_size_filters',
            field=models.BooleanField(default=False, verbose_name='Show portfolio size buttons'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_portfolio_style_filters',
            field=models.BooleanField(default=True, verbose_name='Show portfolio style buttons'),
        ),
    ]
