# Generated by Django 5.2.6 on 2026-07-08 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#8B0000', help_text='Hex colour for the filter chip, e.g. #8B0000', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tattoo style',
                'verbose_name_plural': 'Tattoo styles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('black_grey', 'Black & Grey'), ('color', 'Colour')], default='black_grey', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the homepage featured grid.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='artists.artist')),
                ('styles', models.ManyToManyField(blank=True, related_name='portfolio_items', to='portfolio.tattoostyle')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
