# Generated by Django 5.2.16 on 2026-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_sync_enabled', models.BooleanField(default=True, help_text='თუ ჩართულია, სკრიპტი ყოველდღიურად ან მითითებულ ინტერვალში შეამოწმებს პოსტებს.', verbose_name='ავტომატური შემოწმება ჩართულია')),
                ('sync_interval_hours', models.PositiveIntegerField(default=24, help_text='მაგ. 24 (ყოველდღე) ან 48 (ყოველ 2 დღეში)', verbose_name='შემოწმების ინტერვალი (საათებში)')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='ბოლო შემოწმების თარიღი')),
                ('last_status', models.CharField(default='idle', max_length=50, verbose_name='ბოლო სტატუსი')),
                ('last_error_message', models.TextField(blank=True, verbose_name='ბოლო შეცდომის შეტყობინება')),
            ],
            options={
                'verbose_name': 'Instagram სინქრონიზაციის კონფიგურაცია',
                'verbose_name_plural': 'Instagram სინქრონიზაციის კონფიგურაცია',
            },
        ),
        migrations.CreateModel(
            name='InstagramSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='თარიღი')),
                ('status', models.CharField(choices=[('success', 'წარმატებული'), ('failed', 'შეცდომა'), ('warning', 'გაფრთხილება')], default='success', max_length=20, verbose_name='სტატუსი')),
                ('posts_fetched', models.PositiveIntegerField(default=0, verbose_name='წამოღებული პოსტები')),
                ('items_created', models.PositiveIntegerField(default=0, verbose_name='შექმნილი ნამუშევრები')),
                ('details', models.TextField(blank=True, verbose_name='დეტალები / ლოგი')),
            ],
            options={
                'verbose_name': 'Instagram შემოწმების ლოგი',
                'verbose_name_plural': 'Instagram შემოწმების ლოგები',
                'ordering': ['-created_at'],
            },
        ),
    ]
