# Generated by Django 5.2.16 on 2026-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsyncconfig',
            name='facebook_page_url',
            field=models.URLField(default='https://www.facebook.com/tattooskystudio', help_text='სტუდიის ოფიციალური Facebook გვერდი (მაგ: https://www.facebook.com/tattooskystudio)', verbose_name='Facebook გვერდის ბმული'),
        ),
        migrations.AddField(
            model_name='instagramsyncconfig',
            name='instagram_account_url',
            field=models.URLField(default='https://www.instagram.com/tattooskystudio/', help_text='სტუდიის ოფიციალური Instagram გვერდი (მაგ: https://www.instagram.com/tattooskystudio/)', verbose_name='Instagram ანგარიშის ბმული'),
        ),
    ]
