# Generated by Django 5.2.16 on 2026-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_instagramsyncconfig_facebook_page_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsyncconfig',
            name='instagram_access_token',
            field=models.CharField(blank=True, help_text='Instagram Graph API Access Token პირდაპირი სინქრონიზაციისთვის', max_length=500, verbose_name='Meta Access Token (არასავალდებულო)'),
        ),
        migrations.AddField(
            model_name='instagramsyncconfig',
            name='instagram_session_id',
            field=models.CharField(blank=True, help_text='Instagram-ის sessionid კუკი შეზღუდვების გვერდის ავლით წამოსაღებად', max_length=200, verbose_name='Instagram Session ID (არასავალდებულო)'),
        ),
    ]
