# Generated by Django 5.2.16 on 2026-08-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_instagramsyncconfig_instagram_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsyncconfig',
            name='facebook_access_token',
            field=models.CharField(blank=True, help_text='Facebook Page Access Token (თუ განსხვავდება Instagram-ის ტოკენისგან)', max_length=500, verbose_name='Facebook Page Access Token'),
        ),
        migrations.AddField(
            model_name='instagramsyncconfig',
            name='facebook_page_id',
            field=models.CharField(blank=True, help_text='მაგ: 100987654321000 (Facebook Graph API-სთვის)', max_length=100, verbose_name='Facebook Page ID'),
        ),
        migrations.AddField(
            model_name='instagramsyncconfig',
            name='instagram_account_id',
            field=models.CharField(blank=True, help_text='მაგ: 17841400000000000 (Meta Graph API-სთვის)', max_length=100, verbose_name='Instagram Business Account ID'),
        ),
        migrations.AlterField(
            model_name='instagramsyncconfig',
            name='instagram_access_token',
            field=models.CharField(blank=True, help_text='Meta / Instagram Graph API Access Token (User or Page Access Token)', max_length=500, verbose_name='Instagram / Meta Access Token'),
        ),
        migrations.AlterField(
            model_name='instagramsyncconfig',
            name='instagram_session_id',
            field=models.CharField(blank=True, help_text='Instagram-ის sessionid კუკი შეზღუდვების გვერდის ავლით წამოსაღებად', max_length=200, verbose_name='Instagram Session ID (Cookie Fallback)'),
        ),
    ]
