# Generated by Django 5.2.6 on 2026-07-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Studio value',
                'verbose_name_plural': 'Studio values',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_eyebrow',
            field=models.CharField(blank=True, default='Our Story', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_story',
            field=models.TextField(blank=True, help_text='Full studio story shown on the About page.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_title',
            field=models.CharField(blank=True, default='About the Studio', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='artists_eyebrow',
            field=models.CharField(blank=True, default='The Coven', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='artists_title',
            field=models.CharField(blank=True, default='Meet Our Artists', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_band_label',
            field=models.CharField(blank=True, default='Book Appointment', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_band_text',
            field=models.TextField(blank=True, default="Book a consultation with one of our artists and let's design something eternal."),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_band_title',
            field=models.CharField(blank=True, default='Ready for your next piece?', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_primary_label',
            field=models.CharField(blank=True, default='Book Appointment', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_secondary_label',
            field=models.CharField(blank=True, default='Meet Our Artists', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='featured_eyebrow',
            field=models.CharField(blank=True, default='Latest Ink', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='featured_title',
            field=models.CharField(blank=True, default='Featured Portfolio', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_bg',
            field=models.ImageField(blank=True, help_text='Optional hero background image (dark works best).', null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Gothic Tattoo Studio · Tbilisi', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Gothic ink. Timeless art. — where dark artistry becomes permanent. Bespoke blackwork, realism and gothic ink by resident masters.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(blank=True, default='Sky', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_accent',
            field=models.CharField(blank=True, default='tattoo', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_artists_teaser',
            field=models.BooleanField(default=True, verbose_name='Show artists section'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_featured',
            field=models.BooleanField(default=True, verbose_name='Show featured section'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_styles_strip',
            field=models.BooleanField(default=True, verbose_name='Show styles strip'),
        ),
    ]
