# Generated by Django 5.2.6 on 2026-07-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studiovalue_sitesetting_about_eyebrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='float_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Float Email Address'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='float_facebook',
            field=models.URLField(blank=True, verbose_name='Float Facebook Link'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='float_instagram',
            field=models.URLField(blank=True, verbose_name='Float Instagram Link'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='float_whatsapp',
            field=models.CharField(blank=True, help_text='e.g. +995599123456 or a wa.me link', max_length=100, verbose_name='Float WhatsApp Number or Link'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Optional hero background video (MP4 format). If uploaded, it plays instead of the image.', null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_float_button',
            field=models.BooleanField(default=True, verbose_name='Show Floating Contact Button'),
        ),
    ]
