# Generated by Django 5.2.6 on 2026-07-11 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio gallery image',
                'verbose_name_plural': 'Portfolio gallery images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
