# Generated by Django 5.2.16 on 2026-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='instagram_permalink',
            field=models.URLField(blank=True, help_text='Direct link to Instagram post.'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='instagram_post_id',
            field=models.CharField(blank=True, help_text='Unique ID of synced Instagram post to prevent duplicates.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_from_instagram',
            field=models.BooleanField(default=False),
        ),
    ]
