# Generated by Django 5.2.16 on 2026-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioitem_instagram_permalink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='facebook_permalink',
            field=models.URLField(blank=True, help_text='Direct link to Facebook post.'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='facebook_post_id',
            field=models.CharField(blank=True, help_text='Unique ID of synced Facebook post to prevent duplicates.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_from_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], default='manual', max_length=20),
        ),
    ]
