# Generated by Django 5.2.6 on 2026-07-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('role', models.CharField(blank=True, help_text='e.g. Resident Artist, Founder, Guest Artist', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='artists/avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='artists/covers/')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('provider', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='youtube', max_length=20)),
                ('video_url', models.URLField(help_text='Full YouTube / Vimeo URL. The embed is generated automatically.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='artists/reels/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
