# Generated by Django 5.2.6 on 2026-07-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Paste a public Instagram post/reel or TikTok video URL. The platform is detected automatically.')),
                ('platform', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok')], help_text='Auto-detected from the URL.', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Social post',
                'verbose_name_plural': 'Social feed',
                'ordering': ['order', 'id'],
            },
        ),
    ]
