# Generated by Django 5.2.16 on 2026-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_socialpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='instagram_hashtag',
            field=models.CharField(blank=True, help_text='Hashtag for portfolio sync without #, e.g. avtosailor', max_length=60),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Instagram handle without @, e.g. avtosailor', max_length=60),
        ),
    ]
